/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sale.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 09-26-2015
 * 
 * XDoclet definition:
 * @struts.form name="customerForm"
 */
public class CustomerForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** cusid property */
	private String cusid;
	
	/** companame_en property */
	private String companame_en;
	
	/** companame_th property */
	private String companame_th;
	
	/** cusname property */
	private String cusname;
	
	/** position property */
	private String position;

	/** mail property */
	private String mail;

	/** address property */
	private String address;

	/** tel08 property */
	private String tel08;
	
	/** tel02 property */
	private String tel02;
	
	/** fax property */
	private String fax;


	private String submit,search;
	
	private String delete,update;
	
	private String project;
	
	private String status;
	
	public CustomerForm(){}
	public CustomerForm(String s1, String s2) {
		
		this.cusid = s1;
		this.cusname = s2;
		
		
		
	}
	
	
	

	public CustomerForm(String cusid, 
			String companame_en,
			String companame_th,
			String cusname,
			String position,
			String mail,
			String address,
			String tel08,
			String tel02,
			String fax) {
		
			this.cusid = cusid;
			this.companame_en = companame_en;
			this.companame_th = companame_th;
			this.cusname = cusname;
			this.position = position;
			this.mail = mail;
			this.address = address;
			this.tel08 = tel08;
			this.tel02 = tel02;
			this.fax = fax;
		
		// TODO Auto-generated constructor stub
	}
	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the cusid.
	 * @return String
	 */
	public String getCusid() {
		return cusid;
	}

	/** 
	 * Set the cusid.
	 * @param cusid The cusid to set
	 */
	public void setCusid(String cusid) {
		this.cusid = cusid;
	}

	/** 
	 * Returns the companame_en.
	 * @return String
	 */
	public String getCompaname_en() {
		return companame_en;
	}

	/** 
	 * Set the companame_en.
	 * @param companame_en The companame_en to set
	 */
	public void setCompaname_en(String companame_en) {
		this.companame_en = companame_en;
	}
	
	public String getCompaname_th() {
		return companame_th;
	}

	public void setCompaname_th(String companame_th) {
		this.companame_th = companame_th;
	}
	
	/** 
	 * Returns the cusname.
	 * @return String
	 */
	public String getCusname() {
		return cusname;
	}

	/** 
	 * Set the cusname.
	 * @param cusname The cusname to set
	 */
	public void setCusname(String cusname) {
		this.cusname = cusname;
	}
	
	/** 
	 * Returns the position.
	 * @return String
	 */
	public String getPosition() {
		return position;
	}

	/** 
	 * Set the position.
	 * @param position The position to set
	 */
	public void setPosition(String position) {
		this.position = position;
	}

	/** 
	 * Returns the mail.
	 * @return String
	 */
	public String getMail() {
		return mail;
	}

	/** 
	 * Set the mail.
	 * @param mail The mail to set
	 */
	public void setMail(String mail) {
		this.mail = mail;
	}

	/** 
	 * Returns the address.
	 * @return String
	 */
	public String getAddress() {
		return address;
	}

	/** 
	 * Set the address.
	 * @param address The address to set
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/** 
	 * Returns the tel08.
	 * @return String
	 */
	public String getTel08() {
		return tel08;
	}

	/** 
	 * Set the tel08.
	 * @param tel08 The tel08 to set
	 */
	public void setTel08(String tel08) {
		this.tel08 = tel08;
	}
	
	/** 
	 * Returns the tel02.
	 * @return String
	 */
	public String getTel02() {
		return tel02;
	}

	/** 
	 * Set the tel02.
	 * @param tel02 The tel02 to set
	 */
	public void setTel02(String tel02) {
		this.tel02 = tel02;
	}
		
	/** 
	 * Returns the fax.
	 * @return String
	 */
	public String getFax() {
		return fax;
	}

	/** 
	 * Set the fax.
	 * @param fax The fax to set
	 */
	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getSubmit() {
		return submit;
	}

	public void setSubmit(String submit) {
		this.submit = submit;
	}

	public String getSearch() {
		return search;
	}

	public void setSearch(String search) {
		this.search = search;
	}
	
	public String getDelete() {
		return delete;
	}

	public void setDelete(String delete) {
		this.delete = delete;
	}

	public String getUpdate() {
		return update;
	}
	
	public String getProject() {
		return project;
	}

	public void setProject(String project) {
		this.project = project;
	}

	public void setUpdate(String update) {
		this.update = update;
	}
	
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
	
}
