/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sale.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 10-06-2015
 * 
 * XDoclet definition:
 * @struts.form name="detailForm"
 */
public class DetailForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** id property */
	private String id;

	/** cusid property */
	private String cusid;
	
	private String proid;
	
	/** statusid property */
	private String statusid;

	/** remark property */
	private String remark;
	
	private String date;
	
	private String username;
	
	
	private String submit, search;
	
	private String delete;
	
	private String showlist;
	

	private String cusname, proname, statusname, empname;
	
	private String companame_th;
	
	
	private String getusername;
	
	private String username1;
	
	
	private String project;
	
	private String status;
	
	
	
	/*
	 * Generated Methods
	 */

	public DetailForm(){}
	public DetailForm(String id, String cusname, String companame_th, String proname, String statusname, String remark, String date, String empname) {
		this.id = id;
		this.cusname = cusname;
		this.companame_th = companame_th;
		this.proname = proname;
		this.statusname = statusname;
		this.remark = remark;
		this.date = date;
		this.empname = empname;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the id.
	 * @return String
	 */
	public String getId() {
		return id;
	}

	/** 
	 * Set the id.
	 * @param id The id to set
	 */
	public void setId(String id) {
		this.id = id;
	}

	/** 
	 * Returns the cusid.
	 * @return String
	 */
	public String getCusid() {
		return cusid;
	}

	/** 
	 * Set the cusid.
	 * @param cusid The cusid to set
	 */
	public void setCusid(String cusid) {
		this.cusid = cusid;
	}
	
	public String getProid() {
		return proid;
	}

	public void setProid(String proid) {
		this.proid = proid;
	}
	
	/** 
	 * Returns the statusid.
	 * @return String
	 */
	public String getStatusid() {
		return statusid;
	}

	/** 
	 * Set the statusid.
	 * @param statusid The statusid to set
	 */
	public void setStatusid(String statusid) {
		this.statusid = statusid;
	}
	
	/** 
	 * Returns the remark.
	 * @return String
	 */
	public String getRemark() {
		return remark;
	}

	/** 
	 * Set the remark.
	 * @param remark The remark to set
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}
	
	public String getDate() {
		return date;
	}

	public void setDate(String date) {
		this.date = date;
	}
	
	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getSubmit() {
		return submit;
	}

	public void setSubmit(String submit) {
		this.submit = submit;
	}

	public String getSearch() {
		return search;
	}

	public void setSearch(String search) {
		this.search = search;
	}

	public String getDelete() {
		return delete;
	}

	public void setDelete(String delete) {
		this.delete = delete;
	}
	
	public String getShowlist() {
		return showlist;
	}

	public void setShowlist(String showlist) {
		this.showlist = showlist;
	}

	public String getProject() {
		return project;
	}

	public void setProject(String project) {
		this.project = project;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
	public String getCusname() {
		return cusname;
	}
	public void setCusname(String cusname) {
		this.cusname = cusname;
	}
	public String getProname() {
		return proname;
	}
	public void setProname(String proname) {
		this.proname = proname;
	}
	public String getStatusname() {
		return statusname;
	}
	public void setStatusname(String statusname) {
		this.statusname = statusname;
	}
	public String getCompaname_th() {
		return companame_th;
	}
	public void setCompaname_th(String companameTh) {
		companame_th = companameTh;
	}
	public String getGetusername() {
		return getusername;
	}
	public void setGetusername(String getusername) {
		this.getusername = getusername;
	}
	public String getEmpname() {
		return empname;
	}
	public void setEmpname(String empname) {
		this.empname = empname;
	}
	public String getUsername1() {
		return username1;
	}
	public void setUsername1(String username1) {
		this.username1 = username1;
	}

	
}