/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sale.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 10-05-2015
 * 
 * XDoclet definition:
 * @struts.form name="employeeForm"
 */
public class EmployeeForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** username property */
	private String username;
	
	/** password property */
	private String password;
	
	/** empname property */
	private String empname;
	
	/** position property */
	private String position;

	/** address property */
	private String address;
	
	/** tel property */
	private String tel;
	
	/** mail property */
	private String mail;

	
	private String submit,search;
	
	private String delete,update;
	

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
	
	/** 
	 * Returns the username.
	 * @return String
	 */
	public String getUsername() {
		return username;
	}

	/** 
	 * Set the username.
	 * @param username The username to set
	 */
	public void setUsername(String username) {
		this.username = username;
	}
	
	/** 
	 * Returns the password.
	 * @return String
	 */
	public String getPassword() {
		return password;
	}

	/** 
	 * Set the password.
	 * @param password The password to set
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/** 
	 * Returns the empname.
	 * @return String
	 */
	public String getEmpname() {
		return empname;
	}

	/** 
	 * Set the empname.
	 * @param empname The empname to set
	 */
	public void setEmpname(String empname) {
		this.empname = empname;
	}
	
	/** 
	 * Returns the position.
	 * @return String
	 */
	public String getPosition() {
		return position;
	}

	/** 
	 * Set the position.
	 * @param position The position to set
	 */
	public void setPosition(String position) {
		this.position = position;
	}
	
	/** 
	 * Returns the address.
	 * @return String
	 */
	public String getAddress() {
		return address;
	}

	/** 
	 * Set the address.
	 * @param address The address to set
	 */
	public void setAddress(String address) {
		this.address = address;
	}
	
	/** 
	 * Returns the tel.
	 * @return String
	 */
	public String getTel() {
		return tel;
	}

	/** 
	 * Set the tel.
	 * @param tel The tel to set
	 */
	public void setTel(String tel) {
		this.tel = tel;
	}

	/** 
	 * Returns the mail.
	 * @return String
	 */
	public String getMail() {
		return mail;
	}

	/** 
	 * Set the mail.
	 * @param mail The mail to set
	 */
	public void setMail(String mail) {
		this.mail = mail;
	}

	public String getSubmit() {
		return submit;
	}

	public void setSubmit(String submit) {
		this.submit = submit;
	}

	public String getSearch() {
		return search;
	}

	public void setSearch(String search) {
		this.search = search;
	}

	public String getDelete() {
		return delete;
	}

	public void setDelete(String delete) {
		this.delete = delete;
	}

	public String getUpdate() {
		return update;
	}

	public void setUpdate(String update) {
		this.update = update;
	}
}