/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sale.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 10-16-2015
 * 
 * XDoclet definition:
 * @struts.form name="projectForm"
 */
public class ProjectForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** proname property */
	private String proname;

	/** proid property */
	private String proid;

	/** cusid property */
	private String cusid;
	
	private String cusname;
	
	
	private String submit,search;
	
	private String delete,update;

	/*
	 * Generated Methods
	 */
	public ProjectForm(){}
	public ProjectForm(String proid, String proname, String cusid, String cusname) {
		this.proid = proid;
		this.proname = proname;
		this.cusid = cusid;
		this.cusname = cusname;
		
		
		// TODO Auto-generated constructor stub
	}

	
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the proname.
	 * @return String
	 */
	public String getProname() {
		return proname;
	}

	/** 
	 * Set the proname.
	 * @param proname The proname to set
	 */
	public void setProname(String proname) {
		this.proname = proname;
	}

	/** 
	 * Returns the proid.
	 * @return String
	 */
	public String getProid() {
		return proid;
	}

	/** 
	 * Set the proid.
	 * @param proid The proid to set
	 */
	public void setProid(String proid) {
		this.proid = proid;
	}

	/** 
	 * Returns the cusid.
	 * @return String
	 */
	public String getCusid() {
		return cusid;
	}

	/** 
	 * Set the cusid.
	 * @param cusid The cusid to set
	 */
	public void setCusid(String cusid) {
		this.cusid = cusid;
	}
	public String getSubmit() {
		return submit;
	}
	public void setSubmit(String submit) {
		this.submit = submit;
	}
	public String getSearch() {
		return search;
	}
	public void setSearch(String search) {
		this.search = search;
	}
	public String getDelete() {
		return delete;
	}
	public void setDelete(String delete) {
		this.delete = delete;
	}
	public String getUpdate() {
		return update;
	}
	public void setUpdate(String update) {
		this.update = update;
	}
	public String getCusname() {
		return cusname;
	}
	public void setCusname(String cusname) {
		this.cusname = cusname;
	}
}