/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sale.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 10-19-2015
 * 
 * XDoclet definition:
 * @struts.form name="statusForm"
 */
public class StatusForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** statusname property */
	private String statusname;

	/** statusid property */
	private String statusid;
	
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the statusname.
	 * @return String
	 */
	public String getStatusname() {
		return statusname;
	}

	/** 
	 * Set the statusname.
	 * @param statusname The statusname to set
	 */
	public void setStatusname(String statusname) {
		this.statusname = statusname;
	}

	/** 
	 * Returns the statusid.
	 * @return String
	 */
	public String getStatusid() {
		return statusid;
	}

	/** 
	 * Set the statusid.
	 * @param statusid The statusid to set
	 */
	public void setStatusid(String statusid) {
		this.statusid = statusid;
	}

}