/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sale.struts.action;

import java.io.IOException;
import java.io.UnsupportedEncodingException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import java.util.*;

import com.sale.struts.data.tblcustomer;
import com.sale.struts.form.CustomerForm;

/** 
 * MyEclipse Struts
 * Creation date: 09-26-2015
 * 
 * XDoclet definition:
 * @struts.action path="/customer" name="customerForm" input="/customer.jsp" scope="request" validate="true"
 */
public class CustomerAction extends Action {
	private CustomerForm customerFrom;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		CustomerForm customerForm = (CustomerForm) form;// TODO Auto-generated method stub
		
		HttpSession session = request.getSession();
		if(session.getAttribute("username") == null){
			return mapping.findForward("nologin");
		}
		
		String cusid=null, companame_en=null, companame_th=null, cusname=null, position=null, mail=null, address=null, tel08=null, tel02=null, fax=null, 
		submit =null, search=null, delete=null, update=null, status=null;
		
		
			submit = request.getParameter("submit");
			search = request.getParameter("search");
			delete = request.getParameter("delete");
			update = request.getParameter("update");
			
		
		tblcustomer tbl = new tblcustomer();
		
		if(submit != "" && submit != null){
			try {
				cusid = customerForm.getCusid();
				companame_en = customerForm.getCompaname_en();
				companame_th = new String(customerForm.getCompaname_th().getBytes("ISO8859_1"),"utf-8");
				cusname = new String(customerForm.getCusname().getBytes("ISO8859_1"),"utf-8");
				position = new String(customerForm.getPosition().getBytes("ISO8859_1"),"utf-8");
				mail = customerForm.getMail();
				address = new String(customerForm.getAddress().getBytes("ISO8859_1"),"utf-8");
				tel08 = customerForm.getTel08();
				tel02 = customerForm.getTel02();
				fax = customerForm.getFax();
				
				status = customerForm.getStatus();
				
				tbl.insert_to_customer(cusid, companame_en, companame_th, cusname, position, mail, address, tel08, tel02, fax);
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
			customerForm.setCusid("");
			customerForm.setCompaname_en("");
			customerForm.setCompaname_th("");
			customerForm.setCusname("");
			customerForm.setPosition("");
			customerForm.setMail("");
			customerForm.setAddress("");
			customerForm.setTel08("");
			customerForm.setTel02("");
			customerForm.setFax("");
			
			
		}else if(search != "" && search != null){
			String[] result = new String[10];
			try {
				cusid = customerForm.getCusid();
				companame_en = customerForm.getCompaname_en();
				companame_th = new String(customerForm.getCompaname_th().getBytes("ISO8859_1"),"utf-8");
				cusname = new String(customerForm.getCusname().getBytes("ISO8859_1"),"utf-8");
				position = new String(customerForm.getPosition().getBytes("ISO8859_1"),"utf-8");
				mail = customerForm.getMail();
				address = new String(customerForm.getAddress().getBytes("ISO8859_1"),"utf-8");
				tel08 = customerForm.getTel08();
				tel02 = customerForm.getTel02();
				fax = customerForm.getFax();
				
				status = customerForm.getStatus();
				
				result = tbl.select_from_customer(cusid, cusname);
				
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
			customerForm.setCusid(result[0]);
			customerForm.setCompaname_en(result[1]);
			customerForm.setCompaname_th(result[2]);
			customerForm.setCusname(result[3]);
			customerForm.setPosition(result[4]);
			customerForm.setMail(result[5]);
			customerForm.setAddress(result[6]);
			customerForm.setTel08(result[7]);
			customerForm.setTel02(result[8]);
			customerForm.setFax(result[9]);
			
			
		}else if(delete != "" && delete != null){
			try {
				cusid = customerForm.getCusid();
				companame_en = customerForm.getCompaname_en();
				companame_th = new String(customerForm.getCompaname_th().getBytes("ISO8859_1"),"utf-8");
				cusname = new String(customerForm.getCusname().getBytes("ISO8859_1"),"utf-8");
				position = new String(customerForm.getPosition().getBytes("ISO8859_1"),"utf-8");
				mail = customerForm.getMail();
				address = new String(customerForm.getAddress().getBytes("ISO8859_1"),"utf-8");
				tel08 = customerForm.getTel08();
				tel02 = customerForm.getTel02();
				fax = customerForm.getFax();
				
				status = customerForm.getStatus();
				
				tbl.delete_from_customer(cusid);
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
			customerForm.setCusid("");
			customerForm.setCompaname_en("");
			customerForm.setCompaname_th("");
			customerForm.setCusname("");
			customerForm.setPosition("");
			customerForm.setMail("");
			customerForm.setAddress("");
			customerForm.setTel08("");
			customerForm.setTel02("");
			customerForm.setFax("");
			
			
		}else if(update != "" && update != null){
			try {
				cusid = customerForm.getCusid();
				companame_en = customerForm.getCompaname_en();
				companame_th = new String(customerForm.getCompaname_th().getBytes("ISO8859_1"),"utf-8");
				cusname = new String(customerForm.getCusname().getBytes("ISO8859_1"),"utf-8");
				position = new String(customerForm.getPosition().getBytes("ISO8859_1"),"utf-8");
				mail = customerForm.getMail();
				address = new String(customerForm.getAddress().getBytes("ISO8859_1"),"utf-8");
				tel08 = customerForm.getTel08();
				tel02 = customerForm.getTel02();
				fax = customerForm.getFax();
				
				status = customerForm.getStatus();
				
				tbl.update_customer(cusid, companame_en, companame_th, cusname, position, mail, address, tel08, tel02, fax);
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
			customerForm.setCusid("");
			customerForm.setCompaname_en("");
			customerForm.setCompaname_th("");
			customerForm.setCusname("");
			customerForm.setPosition("");
			customerForm.setMail("");
			customerForm.setAddress("");
			customerForm.setTel08("");
			customerForm.setTel02("");
			customerForm.setFax("");
					
		}
		
		return mapping.findForward("success");
	}
}
