/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sale.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.sale.struts.data.tblemployee;
import com.sale.struts.data.tbllogin;
import com.sale.struts.form.LoginForm;

/** 
 * MyEclipse Struts
 * Creation date: 10-20-2015
 * 
 * XDoclet definition:
 * @struts.action path="/login" name="loginForm" input="/login.jsp" scope="request" validate="true"
 */
public class LoginAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		LoginForm loginForm = (LoginForm) form;// TODO Auto-generated method stub
		tblemployee tblemp = new tblemployee();
		String forwardText = "";
		
		HttpSession session = request.getSession();
		
		String username, password, login = null;
		
		username = loginForm.getUsername();
		password = request.getParameter("password");
		
		
		login = loginForm.getLogin();
		
		
		tbllogin tbl = new tbllogin();
		
		if(tblemp.employee_login(username, password)){
			session.setAttribute("username", username);
			forwardText = "success";
		}else{
			forwardText = "nologin";
			request.setAttribute("alert", "Username or Password Incorrect");
		}
		/////Putsing Jas Aum paa
		return mapping.findForward(forwardText);
	}
}