/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sale.struts.action;

import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.sale.struts.data.tblcustomer;
import com.sale.struts.data.tblproject;
import com.sale.struts.form.DetailForm;
import com.sale.struts.form.ProjectForm;



/** 
 * MyEclipse Struts
 * Creation date: 10-16-2015
 * 
 * XDoclet definition:
 * @struts.action path="/project" name="projectForm" input="/project.jsp" scope="request" validate="true"
 */
public class ProjectAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ProjectForm projectForm = (ProjectForm) form;// TODO Auto-generated method stub
		
		HttpSession session = request.getSession();
		if(session.getAttribute("username") == null){
			return mapping.findForward("nologin");
		}
		
		String proid=null, proname=null, cusid=null, submit =null, search=null, delete=null, update=null, username = null, cusname=null;
		
		
		proid = projectForm.getProid();
		proname = projectForm.getProname();
		cusid = projectForm.getCusid();
		cusname = projectForm.getCusname();
		
		username = (String) session.getAttribute("username");
		
		submit = request.getParameter("submit");
		search = projectForm.getSearch();
		delete = request.getParameter("delete");
		update = request.getParameter("update");
		
		
		
		tblproject tbl = new tblproject();
		tblproject tblp = new tblproject();
		tblcustomer tblc = new tblcustomer();
		
		
		
		if(submit != "" && submit != null){
			
			try {
				proname = new String(projectForm.getProname().getBytes("ISO8859_1"),"utf-8");
			} catch (UnsupportedEncodingException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
			
			
			try {
				tblp.insert_to_project(proname, cusid, username);
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
			
			projectForm.setProname("");
			projectForm.setCusid("");
			
			
			List projectlist = tblp.select_project(cusid);
			List customerlist = tblc.select_customer("");
			
			request.setAttribute("projectlist", projectlist);
			request.setAttribute("customerlist", customerlist);
			
			
			
		}else if(search != "" && search != null){
			String[] result = new String[4];
			List projectlist = null;
			List customerlist = null;
			
			try {
				
				
				
				projectlist = tblp.select_project(cusid);
				customerlist = tblc.select_customer("");
				
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
			request.setAttribute("projectlist", projectlist);
			request.setAttribute("customerlist", customerlist);
			
			
			
//			projectForm.setProid(result[0]);
//			projectForm.setProname(result[1]);
//			projectForm.setCusid(result[2]);
			
			
			
		}else if(delete != "" && delete != null){
			try {
				tblp.delete_from_project(proid);
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
			projectForm.setProid("");
			projectForm.setProname("");
			projectForm.setCusid("");
			
			
			List projectlist = tblp.select_project(cusid);
			List customerlist = tblc.select_customer("");
			
			request.setAttribute("projectlist", projectlist);
			request.setAttribute("customerlist", customerlist);
			
			
		}else if(update != "" && update != null){
			try {
				tblp.update_project(proid, proname, cusid);
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
//			projectForm.setProid("");
//			projectForm.setProname("");
//			projectForm.setCusid("");
			
			
			List projectlist = tblp.select_project(cusid);
			List customerlist = tblc.select_customer("");
			
			request.setAttribute("projectlist", projectlist);
			request.setAttribute("customerlist", customerlist);
					
		
		}else{
			String[] result = new String[4];
			List customerlist = null;
			
			try {
				
				
				customerlist = tblc.select_customer("");
				
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
			request.setAttribute("customerlist", customerlist);
			
			projectForm.setProid(result[0]);
			projectForm.setProname(result[1]);
			projectForm.setCusid(result[2]);
			
		
		}
		
		return mapping.findForward("success");
	}
}