/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sale.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.sale.struts.form.ReportForm;

/** 
 * MyEclipse Struts
 * Creation date: 11-19-2015
 * 
 * XDoclet definition:
 * @struts.action path="/report" name="reportForm" input="/form/report.jsp" scope="request" validate="true"
 */
public class ReportAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ReportForm reportForm = (ReportForm) form;// TODO Auto-generated method stub
		return null;
	}
}