/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sale.struts.action;

import java.io.IOException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.sale.struts.data.tblstatus;
import com.sale.struts.form.StatusForm;

/** 
 * MyEclipse Struts
 * Creation date: 10-19-2015
 * 
 * XDoclet definition:
 * @struts.action path="/status" name="statusForm" input="/status.jsp" scope="request" validate="true"
 */
public class StatusAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		StatusForm statusForm = (StatusForm) form;// TODO Auto-generated method stub
		
		HttpSession session = request.getSession();
		if(session.getAttribute("username") == null){
			return mapping.findForward("nologin");
		}
		
		String statusid=null, statusname=null, submit=null, delete=null;
		
		statusid = statusForm.getStatusid();
		statusname = statusForm.getStatusid();
		
		submit = request.getParameter("submit");
		delete = request.getParameter("delete");
		
		
		tblstatus tbls = new tblstatus();
		
		
		if(submit != "" && submit != null){
			
			try {
				tbls.insert_to_status(statusid, statusname);
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
			statusForm.setStatusid("");
			statusForm.setStatusname("");
	
		}else if(delete != "" && delete != null){
			try {
				tbls.delete_from_status(statusid);
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
			statusForm.setStatusid("");
			statusForm.setStatusname("");
	
		}
		
		return mapping.findForward("success");
	}
}